// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ojtask-homepage/BoldEnergetic.tsx": () => import("../components/mockups/ojtask-homepage/BoldEnergetic.tsx"),
  "./components/mockups/ojtask-homepage/DarkImmersive.tsx": () => import("../components/mockups/ojtask-homepage/DarkImmersive.tsx"),
  "./components/mockups/ojtask-homepage/LightEditorial.tsx": () => import("../components/mockups/ojtask-homepage/LightEditorial.tsx")
};
